//! Declares the AST for the language.
//! 
//! Abstract Syntax Trees (ASTs) represent the structure of the language,
//! generated by the parser. Raw parser ASTs should be optimized further.
//! 
//! We can use this to generate the IR (Intermediate Representation) for the
//! language, which is then used to generate the final machine code.

mod core;
mod ops;
mod types;
mod prim_expr;
mod nary_expr;
mod expr;
mod functions;
mod flow;
mod utils;

pub use self::core::*;
pub use self::ops::*;
pub use self::types::*;
pub use self::prim_expr::*;
pub use self::nary_expr::*;
pub use self::expr::*;
pub use self::functions::*;
pub use self::flow::*;
pub use self::utils::*;